name: Main
on: [push, pull_request]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build pkg-config libglib2.0-dev libpixman-1-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: ./configure --target-list=arm-softmmu --disable-vnc --disable-curses --disable-sdl
      - name: Make
        run: make -j $(nproc)
      - name: Check
        run: make -j $(nproc) check
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/qemu-system-arm
